# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-06 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadCsv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_csv', models.FileField(upload_to='Files')),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
