# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-07 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20180206_2259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadCsv',
        ),
    ]
